version: '3.5'

x-services-volume:
  &laravelup-volume
  type: bind
  source: ./laravelup
  target: /laravelup
 
services:
    # mysql5.7.22
    mydbup:
        # image name
        image: mysql:5.7.22
        # Password and user name of mysql
        environment:
           MYSQL_DATABASE:  tmss_ict_dev
           MYSQL_ROOT_PASSWORD: root
           MYSQL_PASSWORD: root
           MYSQL_USER: root
           MYSQL_ALLOW_EMPTY_PASSWORD: 'YES'
        # Which port should be exposed
        ports:
            - 3306:3306
        container_name: mydbup
        volumes:
            # Save the data in named "Volumes" of Docker
            - db-store:/var/lib/mysql
            # Or use the local file
            # - ./docker_db_data/mysql:/var/lib/mysql
            # Where to save the mysql's log
            - ./logs:/var/log/mysql:z
            # Where to load the my.cnf
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:z
        # Which network this container belongs to.
        networks:
            - app_net
    # The container of laravelup
    laravelup:
        build:
            # Wnere to find the "Dockerfile".
            context: .
            dockerfile: docker/laravelup/Dockerfile
        working_dir: /laravelup
        volumes:
            # Where the source code should be saved.
            - <<: *laravelup-volume
            # Where the bash file is (which is executed for the build)
            - ./docker/laravelup/laravelup_build.sh:/laravelup_build.sh:z
            # Where to save laravelup's log files
            - ./logs:/var/log/php
            # Where to load php.ini.
            - ./docker/laravelup/php.ini:/usr/local/etc/php/php.ini
        # Wait until mydbup container is ready.
        depends_on:
            - mydbup
        container_name: laravelup
        # Which network this container belongs to.
        networks:
            - app_net
    # nginxup 1.17
    nginxup:
        # image name
        image: nginx:1.17-alpine
        # Wait until "laravelup" container is ready
        depends_on:
        - laravelup
        # Which port should be exposed
        ports:
        - 8080:80
        volumes:
        # Where to find the files to serve
        - *laravelup-volume
        # Where to save nginx logs.
        - ./logs:/var/log/nginx
        # Where to load default.conf.
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: nginxup
        # Which network this container belongs to.
        networks:
            - app_net
    #phpmyadminup        
    phpmyadminup:
        image: phpmyadmin
        depends_on:
        - nginxup
        ports:
            - "7000:80"
        links:
            - mydbup:mydbup
        environment:
            PMA_HOST: mydbup
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
        container_name: phpmyadminup
        networks:
            - app_net
            
networks:
    # Containers in same network can access each other by using its container name as host name
    app_net:
        driver: "bridge"
volumes:
    db-store:
